definitions:
  GenericError:
    description: GenericError is a generic error message returned by a server
    properties:
      message:
        type: string
        x-go-name: Message
    type: object
    x-go-package: _/F_/Computer/Projects/Coding/Go/simple-go-todo-list
  Todo:
    description: Todo defines the structure for a Item in the Todo list
    properties:
      Description:
        description: the descirption of the Todo item
        maxLength: 255
        type: string
      Id:
        description: the id for the Todo Item
        format: int64
        minimum: 1
        type: integer
      Name:
        description: the name for this Todo Item
        maxLength: 255
        type: string
    required:
    - Name
    - Description
    type: object
    x-go-package: _/F_/Computer/Projects/Coding/Go/simple-go-todo-list
  ValidationError:
    description: ValidationError is a collection of validation error messages
    properties:
      messages:
        items:
          type: string
        type: array
        x-go-name: Messages
    type: object
    x-go-package: _/F_/Computer/Projects/Coding/Go/simple-go-todo-list
paths:
  /Todo/{id}:
    delete:
      consumes:
      - application/json
      description: Deletes a Todo
      operationId: deleteTodo
      parameters:
      - description: The id of the Todo List Item for which the operation relates
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: Id
      produces:
      - application/json
      responses:
        "201":
          $ref: '#/responses/noContentResponse'
        "404":
          $ref: '#/responses/errorResponse'
        "501":
          $ref: '#/responses/errorResponse'
      schemes:
      - http
      tags:
      - todos
  /todos:
    get:
      consumes:
      - application/json
      description: Return a list of Todos from the database
      operationId: getTodos
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/todosResponse'
        "404":
          $ref: '#/responses/errorResponse'
      schemes:
      - http
      tags:
      - todos
    post:
      consumes:
      - application/json
      description: Adds a new Todo Item
      operationId: addTodo
      produces:
      - application/json
      responses:
        "201":
          $ref: '#/responses/noContentResponse'
        "404":
          $ref: '#/responses/errorResponse'
        "501":
          $ref: '#/responses/errorResponse'
      schemes:
      - http
      tags:
      - todos
responses:
  errorResponse:
    description: Generic error message returned as a string
    schema:
      $ref: '#/definitions/GenericError'
  errorValidation:
    description: Validation errors defined as an array of strings
    schema:
      $ref: '#/definitions/ValidationError'
  noContentResponse:
    description: No content is returned by this API endpoint
  todoResponse:
    description: Data structure representing a single Todo List Item
    schema:
      $ref: '#/definitions/Todo'
  todosResponse:
    description: Data structure representing a List of Todo List Items
    schema:
      items:
        $ref: '#/definitions/Todo'
      type: array
swagger: "2.0"
